
redis:
  image: redis
  container_name: db
  volumes:
    - ./data:/data
  expose:
    - 6379

app:
  links:
    - redis
  build: ./
  volumes:
    - ./:/usr/src/app
  ports:
    - 3000:3000
  env_file: .env
  command:
    sh -c 'yarn install && node index.js'
